//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace CardChequeModule.WebRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OBLAPPSoap", Namespace="http://onebank.com.bd/")]
    public partial class OBLAPP : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmployeeNameByOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIDbyEmployeeIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPreDeptNameByOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPreDeptIdByOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPreBranchIdByOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPreDesigByOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGlobalEnumOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDeptNameByDeptIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGlobalDeptOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetByUserIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetByUserBrOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetByUserIDCheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGlobalAllBranchOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OBLAPP() {
            this.Url = global::CardChequeModule.Properties.Settings.Default.CardChequeModule_WebRef_OBLAPP;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetAllUserCompletedEventHandler GetAllUserCompleted;
        
        /// <remarks/>
        public event GetEmployeeNameByCompletedEventHandler GetEmployeeNameByCompleted;
        
        /// <remarks/>
        public event GetIDbyEmployeeIdCompletedEventHandler GetIDbyEmployeeIdCompleted;
        
        /// <remarks/>
        public event GetPreDeptNameByCompletedEventHandler GetPreDeptNameByCompleted;
        
        /// <remarks/>
        public event GetPreDeptIdByCompletedEventHandler GetPreDeptIdByCompleted;
        
        /// <remarks/>
        public event GetPreBranchIdByCompletedEventHandler GetPreBranchIdByCompleted;
        
        /// <remarks/>
        public event GetPreDesigByCompletedEventHandler GetPreDesigByCompleted;
        
        /// <remarks/>
        public event GetGlobalEnumCompletedEventHandler GetGlobalEnumCompleted;
        
        /// <remarks/>
        public event GetDeptNameByDeptIdCompletedEventHandler GetDeptNameByDeptIdCompleted;
        
        /// <remarks/>
        public event GetGlobalDeptCompletedEventHandler GetGlobalDeptCompleted;
        
        /// <remarks/>
        public event GetByUserIDCompletedEventHandler GetByUserIDCompleted;
        
        /// <remarks/>
        public event GetByUserBrCompletedEventHandler GetByUserBrCompleted;
        
        /// <remarks/>
        public event GetByUserIDCheckCompletedEventHandler GetByUserIDCheckCompleted;
        
        /// <remarks/>
        public event GetGlobalAllBranchCompletedEventHandler GetGlobalAllBranchCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://onebank.com.bd/HelloWorld", RequestNamespace="http://onebank.com.bd/", ResponseNamespace="http://onebank.com.bd/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://onebank.com.bd/GetAllUser", RequestNamespace="http://onebank.com.bd/", ResponseNamespace="http://onebank.com.bd/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAllUser() {
            object[] results = this.Invoke("GetAllUser", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllUserAsync() {
            this.GetAllUserAsync(null);
        }
        
        /// <remarks/>
        public void GetAllUserAsync(object userState) {
            if ((this.GetAllUserOperationCompleted == null)) {
                this.GetAllUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllUserOperationCompleted);
            }
            this.InvokeAsync("GetAllUser", new object[0], this.GetAllUserOperationCompleted, userState);
        }
        
        private void OnGetAllUserOperationCompleted(object arg) {
            if ((this.GetAllUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllUserCompleted(this, new GetAllUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://onebank.com.bd/GetEmployeeNameBy", RequestNamespace="http://onebank.com.bd/", ResponseNamespace="http://onebank.com.bd/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetEmployeeNameBy(string EmployeeID) {
            object[] results = this.Invoke("GetEmployeeNameBy", new object[] {
                        EmployeeID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetEmployeeNameByAsync(string EmployeeID) {
            this.GetEmployeeNameByAsync(EmployeeID, null);
        }
        
        /// <remarks/>
        public void GetEmployeeNameByAsync(string EmployeeID, object userState) {
            if ((this.GetEmployeeNameByOperationCompleted == null)) {
                this.GetEmployeeNameByOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmployeeNameByOperationCompleted);
            }
            this.InvokeAsync("GetEmployeeNameBy", new object[] {
                        EmployeeID}, this.GetEmployeeNameByOperationCompleted, userState);
        }
        
        private void OnGetEmployeeNameByOperationCompleted(object arg) {
            if ((this.GetEmployeeNameByCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmployeeNameByCompleted(this, new GetEmployeeNameByCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://onebank.com.bd/GetIDbyEmployeeId", RequestNamespace="http://onebank.com.bd/", ResponseNamespace="http://onebank.com.bd/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long GetIDbyEmployeeId(string EmployeeID) {
            object[] results = this.Invoke("GetIDbyEmployeeId", new object[] {
                        EmployeeID});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void GetIDbyEmployeeIdAsync(string EmployeeID) {
            this.GetIDbyEmployeeIdAsync(EmployeeID, null);
        }
        
        /// <remarks/>
        public void GetIDbyEmployeeIdAsync(string EmployeeID, object userState) {
            if ((this.GetIDbyEmployeeIdOperationCompleted == null)) {
                this.GetIDbyEmployeeIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIDbyEmployeeIdOperationCompleted);
            }
            this.InvokeAsync("GetIDbyEmployeeId", new object[] {
                        EmployeeID}, this.GetIDbyEmployeeIdOperationCompleted, userState);
        }
        
        private void OnGetIDbyEmployeeIdOperationCompleted(object arg) {
            if ((this.GetIDbyEmployeeIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIDbyEmployeeIdCompleted(this, new GetIDbyEmployeeIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://onebank.com.bd/GetPreDeptNameBy", RequestNamespace="http://onebank.com.bd/", ResponseNamespace="http://onebank.com.bd/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPreDeptNameBy(string EmployeeID) {
            object[] results = this.Invoke("GetPreDeptNameBy", new object[] {
                        EmployeeID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPreDeptNameByAsync(string EmployeeID) {
            this.GetPreDeptNameByAsync(EmployeeID, null);
        }
        
        /// <remarks/>
        public void GetPreDeptNameByAsync(string EmployeeID, object userState) {
            if ((this.GetPreDeptNameByOperationCompleted == null)) {
                this.GetPreDeptNameByOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPreDeptNameByOperationCompleted);
            }
            this.InvokeAsync("GetPreDeptNameBy", new object[] {
                        EmployeeID}, this.GetPreDeptNameByOperationCompleted, userState);
        }
        
        private void OnGetPreDeptNameByOperationCompleted(object arg) {
            if ((this.GetPreDeptNameByCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPreDeptNameByCompleted(this, new GetPreDeptNameByCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://onebank.com.bd/GetPreDeptIdBy", RequestNamespace="http://onebank.com.bd/", ResponseNamespace="http://onebank.com.bd/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetPreDeptIdBy(string EmployeeID) {
            object[] results = this.Invoke("GetPreDeptIdBy", new object[] {
                        EmployeeID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetPreDeptIdByAsync(string EmployeeID) {
            this.GetPreDeptIdByAsync(EmployeeID, null);
        }
        
        /// <remarks/>
        public void GetPreDeptIdByAsync(string EmployeeID, object userState) {
            if ((this.GetPreDeptIdByOperationCompleted == null)) {
                this.GetPreDeptIdByOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPreDeptIdByOperationCompleted);
            }
            this.InvokeAsync("GetPreDeptIdBy", new object[] {
                        EmployeeID}, this.GetPreDeptIdByOperationCompleted, userState);
        }
        
        private void OnGetPreDeptIdByOperationCompleted(object arg) {
            if ((this.GetPreDeptIdByCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPreDeptIdByCompleted(this, new GetPreDeptIdByCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://onebank.com.bd/GetPreBranchIdBy", RequestNamespace="http://onebank.com.bd/", ResponseNamespace="http://onebank.com.bd/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetPreBranchIdBy(string EmployeeID) {
            object[] results = this.Invoke("GetPreBranchIdBy", new object[] {
                        EmployeeID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetPreBranchIdByAsync(string EmployeeID) {
            this.GetPreBranchIdByAsync(EmployeeID, null);
        }
        
        /// <remarks/>
        public void GetPreBranchIdByAsync(string EmployeeID, object userState) {
            if ((this.GetPreBranchIdByOperationCompleted == null)) {
                this.GetPreBranchIdByOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPreBranchIdByOperationCompleted);
            }
            this.InvokeAsync("GetPreBranchIdBy", new object[] {
                        EmployeeID}, this.GetPreBranchIdByOperationCompleted, userState);
        }
        
        private void OnGetPreBranchIdByOperationCompleted(object arg) {
            if ((this.GetPreBranchIdByCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPreBranchIdByCompleted(this, new GetPreBranchIdByCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://onebank.com.bd/GetPreDesigBy", RequestNamespace="http://onebank.com.bd/", ResponseNamespace="http://onebank.com.bd/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetPreDesigBy(string EmployeeID) {
            object[] results = this.Invoke("GetPreDesigBy", new object[] {
                        EmployeeID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetPreDesigByAsync(string EmployeeID) {
            this.GetPreDesigByAsync(EmployeeID, null);
        }
        
        /// <remarks/>
        public void GetPreDesigByAsync(string EmployeeID, object userState) {
            if ((this.GetPreDesigByOperationCompleted == null)) {
                this.GetPreDesigByOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPreDesigByOperationCompleted);
            }
            this.InvokeAsync("GetPreDesigBy", new object[] {
                        EmployeeID}, this.GetPreDesigByOperationCompleted, userState);
        }
        
        private void OnGetPreDesigByOperationCompleted(object arg) {
            if ((this.GetPreDesigByCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPreDesigByCompleted(this, new GetPreDesigByCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://onebank.com.bd/GetGlobalEnum", RequestNamespace="http://onebank.com.bd/", ResponseNamespace="http://onebank.com.bd/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetGlobalEnum() {
            object[] results = this.Invoke("GetGlobalEnum", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetGlobalEnumAsync() {
            this.GetGlobalEnumAsync(null);
        }
        
        /// <remarks/>
        public void GetGlobalEnumAsync(object userState) {
            if ((this.GetGlobalEnumOperationCompleted == null)) {
                this.GetGlobalEnumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGlobalEnumOperationCompleted);
            }
            this.InvokeAsync("GetGlobalEnum", new object[0], this.GetGlobalEnumOperationCompleted, userState);
        }
        
        private void OnGetGlobalEnumOperationCompleted(object arg) {
            if ((this.GetGlobalEnumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGlobalEnumCompleted(this, new GetGlobalEnumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://onebank.com.bd/GetDeptNameByDeptId", RequestNamespace="http://onebank.com.bd/", ResponseNamespace="http://onebank.com.bd/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDeptNameByDeptId(int DeptId) {
            object[] results = this.Invoke("GetDeptNameByDeptId", new object[] {
                        DeptId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDeptNameByDeptIdAsync(int DeptId) {
            this.GetDeptNameByDeptIdAsync(DeptId, null);
        }
        
        /// <remarks/>
        public void GetDeptNameByDeptIdAsync(int DeptId, object userState) {
            if ((this.GetDeptNameByDeptIdOperationCompleted == null)) {
                this.GetDeptNameByDeptIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeptNameByDeptIdOperationCompleted);
            }
            this.InvokeAsync("GetDeptNameByDeptId", new object[] {
                        DeptId}, this.GetDeptNameByDeptIdOperationCompleted, userState);
        }
        
        private void OnGetDeptNameByDeptIdOperationCompleted(object arg) {
            if ((this.GetDeptNameByDeptIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDeptNameByDeptIdCompleted(this, new GetDeptNameByDeptIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://onebank.com.bd/GetGlobalDept", RequestNamespace="http://onebank.com.bd/", ResponseNamespace="http://onebank.com.bd/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetGlobalDept() {
            object[] results = this.Invoke("GetGlobalDept", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetGlobalDeptAsync() {
            this.GetGlobalDeptAsync(null);
        }
        
        /// <remarks/>
        public void GetGlobalDeptAsync(object userState) {
            if ((this.GetGlobalDeptOperationCompleted == null)) {
                this.GetGlobalDeptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGlobalDeptOperationCompleted);
            }
            this.InvokeAsync("GetGlobalDept", new object[0], this.GetGlobalDeptOperationCompleted, userState);
        }
        
        private void OnGetGlobalDeptOperationCompleted(object arg) {
            if ((this.GetGlobalDeptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGlobalDeptCompleted(this, new GetGlobalDeptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://onebank.com.bd/GetByUserID", RequestNamespace="http://onebank.com.bd/", ResponseNamespace="http://onebank.com.bd/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetByUserID(string UserID) {
            object[] results = this.Invoke("GetByUserID", new object[] {
                        UserID});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetByUserIDAsync(string UserID) {
            this.GetByUserIDAsync(UserID, null);
        }
        
        /// <remarks/>
        public void GetByUserIDAsync(string UserID, object userState) {
            if ((this.GetByUserIDOperationCompleted == null)) {
                this.GetByUserIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetByUserIDOperationCompleted);
            }
            this.InvokeAsync("GetByUserID", new object[] {
                        UserID}, this.GetByUserIDOperationCompleted, userState);
        }
        
        private void OnGetByUserIDOperationCompleted(object arg) {
            if ((this.GetByUserIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetByUserIDCompleted(this, new GetByUserIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://onebank.com.bd/GetByUserBr", RequestNamespace="http://onebank.com.bd/", ResponseNamespace="http://onebank.com.bd/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetByUserBr(string UserID, string branchCode) {
            object[] results = this.Invoke("GetByUserBr", new object[] {
                        UserID,
                        branchCode});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetByUserBrAsync(string UserID, string branchCode) {
            this.GetByUserBrAsync(UserID, branchCode, null);
        }
        
        /// <remarks/>
        public void GetByUserBrAsync(string UserID, string branchCode, object userState) {
            if ((this.GetByUserBrOperationCompleted == null)) {
                this.GetByUserBrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetByUserBrOperationCompleted);
            }
            this.InvokeAsync("GetByUserBr", new object[] {
                        UserID,
                        branchCode}, this.GetByUserBrOperationCompleted, userState);
        }
        
        private void OnGetByUserBrOperationCompleted(object arg) {
            if ((this.GetByUserBrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetByUserBrCompleted(this, new GetByUserBrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://onebank.com.bd/GetByUserIDCheck", RequestNamespace="http://onebank.com.bd/", ResponseNamespace="http://onebank.com.bd/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetByUserIDCheck(string UserID, string password) {
            object[] results = this.Invoke("GetByUserIDCheck", new object[] {
                        UserID,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetByUserIDCheckAsync(string UserID, string password) {
            this.GetByUserIDCheckAsync(UserID, password, null);
        }
        
        /// <remarks/>
        public void GetByUserIDCheckAsync(string UserID, string password, object userState) {
            if ((this.GetByUserIDCheckOperationCompleted == null)) {
                this.GetByUserIDCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetByUserIDCheckOperationCompleted);
            }
            this.InvokeAsync("GetByUserIDCheck", new object[] {
                        UserID,
                        password}, this.GetByUserIDCheckOperationCompleted, userState);
        }
        
        private void OnGetByUserIDCheckOperationCompleted(object arg) {
            if ((this.GetByUserIDCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetByUserIDCheckCompleted(this, new GetByUserIDCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://onebank.com.bd/GetGlobalAllBranch", RequestNamespace="http://onebank.com.bd/", ResponseNamespace="http://onebank.com.bd/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetGlobalAllBranch() {
            object[] results = this.Invoke("GetGlobalAllBranch", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetGlobalAllBranchAsync() {
            this.GetGlobalAllBranchAsync(null);
        }
        
        /// <remarks/>
        public void GetGlobalAllBranchAsync(object userState) {
            if ((this.GetGlobalAllBranchOperationCompleted == null)) {
                this.GetGlobalAllBranchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGlobalAllBranchOperationCompleted);
            }
            this.InvokeAsync("GetGlobalAllBranch", new object[0], this.GetGlobalAllBranchOperationCompleted, userState);
        }
        
        private void OnGetGlobalAllBranchOperationCompleted(object arg) {
            if ((this.GetGlobalAllBranchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGlobalAllBranchCompleted(this, new GetGlobalAllBranchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetAllUserCompletedEventHandler(object sender, GetAllUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetEmployeeNameByCompletedEventHandler(object sender, GetEmployeeNameByCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmployeeNameByCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmployeeNameByCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetIDbyEmployeeIdCompletedEventHandler(object sender, GetIDbyEmployeeIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIDbyEmployeeIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIDbyEmployeeIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetPreDeptNameByCompletedEventHandler(object sender, GetPreDeptNameByCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPreDeptNameByCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPreDeptNameByCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetPreDeptIdByCompletedEventHandler(object sender, GetPreDeptIdByCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPreDeptIdByCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPreDeptIdByCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetPreBranchIdByCompletedEventHandler(object sender, GetPreBranchIdByCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPreBranchIdByCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPreBranchIdByCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetPreDesigByCompletedEventHandler(object sender, GetPreDesigByCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPreDesigByCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPreDesigByCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetGlobalEnumCompletedEventHandler(object sender, GetGlobalEnumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGlobalEnumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGlobalEnumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetDeptNameByDeptIdCompletedEventHandler(object sender, GetDeptNameByDeptIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDeptNameByDeptIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDeptNameByDeptIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetGlobalDeptCompletedEventHandler(object sender, GetGlobalDeptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGlobalDeptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGlobalDeptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetByUserIDCompletedEventHandler(object sender, GetByUserIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetByUserIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetByUserIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetByUserBrCompletedEventHandler(object sender, GetByUserBrCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetByUserBrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetByUserBrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetByUserIDCheckCompletedEventHandler(object sender, GetByUserIDCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetByUserIDCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetByUserIDCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetGlobalAllBranchCompletedEventHandler(object sender, GetGlobalAllBranchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGlobalAllBranchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGlobalAllBranchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591