//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardChequeModule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRANCHINFO_V
    {
        public long ID { get; set; }
        public string BRANCHCODE { get; set; }
        public string BRANCHNAME { get; set; }
    }
}
