//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using CardChequeModule.Models.MetaData;

namespace CardChequeModule.Models
{
    using System;
    using System.Collections.Generic;

    [MetadataType(typeof(CardChLeafMeta))]
    public partial class CARDCHLEAF
    {
        public CARDCHLEAF()
        {
            this.CARDCHTRAN = new HashSet<CARDCHTRAN>();
        }
    
        public long ID { get; set; }
        public long CHEQUEID { get; set; }
        public string LEAFNO { get; set; }
        public long LEAFSTATUS { get; set; }
        public string REMARKS { get; set; }
        public bool ISACTIVE { get; set; }
        public long CREATEDBY { get; set; }
        public System.DateTime CREATEDON { get; set; }
        public Nullable<long> MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFIEDON { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual CARDCHEREUISITION CARDCHEREUISITION { get; set; }
        public virtual OCCENUMERATION OCCENUMERATION { get; set; }
        public virtual OCCUSER OCCUSER { get; set; }
        public virtual OCCUSER OCCUSER1 { get; set; }
        public virtual ICollection<CARDCHTRAN> CARDCHTRAN { get; set; }
    }
}
