//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardChequeModule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARDCHEREUISITION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARDCHEREUISITION()
        {
            this.CARDCHLEAF = new HashSet<CARDCHLEAF>();
        }
    
        public long ID { get; set; }
        public string CARDNO { get; set; }
        public long BRANCHCODE { get; set; }
        public long STATUS { get; set; }
        public int LEAFNO { get; set; }
        public string LEAFFROM { get; set; }
        public string LEAFTO { get; set; }
        public Nullable<long> LEAFNEXT { get; set; }
        public string REMARKS { get; set; }
        public bool ISACTIVE { get; set; }
        public long CREATEDBY { get; set; }
        public System.DateTime CREATEDON { get; set; }
        public Nullable<long> AUTHORIZEDBY { get; set; }
        public Nullable<System.DateTime> AUTHORIZEDON { get; set; }
        public string REFERENCENO { get; set; }
        public Nullable<long> ESTABLISHMENTBY { get; set; }
        public Nullable<System.DateTime> ESTABLISHMENTON { get; set; }
        public Nullable<long> CALLCENTERBY { get; set; }
        public Nullable<System.DateTime> CALLCENTERON { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
        public Nullable<long> MODIFIDBY { get; set; }
        public Nullable<System.DateTime> MODIFIEDON { get; set; }
    
        public virtual BRANCHINFO BRANCHINFO { get; set; }
        public virtual OCCENUMERATION OCCENUMERATION { get; set; }
        public virtual OCCUSER OCCUSER { get; set; }
        public virtual OCCUSER OCCUSER1 { get; set; }
        public virtual OCCUSER OCCUSER2 { get; set; }
        public virtual OCCUSER OCCUSER3 { get; set; }
        public virtual OCCUSER OCCUSER4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARDCHLEAF> CARDCHLEAF { get; set; }
    }
}
