//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardChequeModule.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OBLCARDCHEQUEEntities : DbContext
    {
        public OBLCARDCHEQUEEntities()
            : base("name=OBLCARDCHEQUEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BRANCHINFO> BRANCHINFO { get; set; }
        public virtual DbSet<CARDCHEREUISITION> CARDCHEREUISITION { get; set; }
        public virtual DbSet<CARDCHLEAF> CARDCHLEAF { get; set; }
        public virtual DbSet<CARDCHTRAN> CARDCHTRAN { get; set; }
        public virtual DbSet<DEPOSIT> DEPOSIT { get; set; }
        public virtual DbSet<OCCENUMERATION> OCCENUMERATION { get; set; }
        public virtual DbSet<OCCEVENTLOG> OCCEVENTLOG { get; set; }
        public virtual DbSet<OCCUSER> OCCUSER { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
