//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using CardChequeModule.Models.MetaData;

namespace CardChequeModule.Models
{
    using System;
    using System.Collections.Generic;

    [MetadataType(typeof(UserMeta))]
    public partial class OCCUSER
    {
        public OCCUSER()
        {
            this.CARDCHEREUISITION = new HashSet<CARDCHEREUISITION>();
            this.CARDCHEREUISITION1 = new HashSet<CARDCHEREUISITION>();
            this.CARDCHEREUISITION2 = new HashSet<CARDCHEREUISITION>();
            this.CARDCHEREUISITION3 = new HashSet<CARDCHEREUISITION>();
            this.CARDCHEREUISITION4 = new HashSet<CARDCHEREUISITION>();
            this.CARDCHEREUISITION5 = new HashSet<CARDCHEREUISITION>();
            this.CARDCHLEAF = new HashSet<CARDCHLEAF>();
            this.CARDCHLEAF1 = new HashSet<CARDCHLEAF>();
            this.CARDCHTRAN = new HashSet<CARDCHTRAN>();
            this.CARDCHTRAN1 = new HashSet<CARDCHTRAN>();
            this.CARDCHTRAN2 = new HashSet<CARDCHTRAN>();
            this.DEPOSIT = new HashSet<DEPOSIT>();
            this.DEPOSIT1 = new HashSet<DEPOSIT>();
            this.DEPOSIT2 = new HashSet<DEPOSIT>();
            this.OCCEVENTLOG = new HashSet<OCCEVENTLOG>();
        }
    
        public long ID { get; set; }
        public string EMPLOYEEID { get; set; }
        public string USERNAME { get; set; }
        public Nullable<long> BRANCH { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
        public Nullable<long> CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public Nullable<long> MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFIEDON { get; set; }
        public Nullable<long> TYPE { get; set; }
    
        public virtual BRANCHINFO BRANCHINFO { get; set; }
        public virtual ICollection<CARDCHEREUISITION> CARDCHEREUISITION { get; set; }
        public virtual ICollection<CARDCHEREUISITION> CARDCHEREUISITION1 { get; set; }
        public virtual ICollection<CARDCHEREUISITION> CARDCHEREUISITION2 { get; set; }
        public virtual ICollection<CARDCHEREUISITION> CARDCHEREUISITION3 { get; set; }
        public virtual ICollection<CARDCHEREUISITION> CARDCHEREUISITION4 { get; set; }
        public virtual ICollection<CARDCHEREUISITION> CARDCHEREUISITION5 { get; set; }
        public virtual ICollection<CARDCHLEAF> CARDCHLEAF { get; set; }
        public virtual ICollection<CARDCHLEAF> CARDCHLEAF1 { get; set; }
        public virtual ICollection<CARDCHTRAN> CARDCHTRAN { get; set; }
        public virtual ICollection<CARDCHTRAN> CARDCHTRAN1 { get; set; }
        public virtual ICollection<CARDCHTRAN> CARDCHTRAN2 { get; set; }
        public virtual ICollection<DEPOSIT> DEPOSIT { get; set; }
        public virtual ICollection<DEPOSIT> DEPOSIT1 { get; set; }
        public virtual ICollection<DEPOSIT> DEPOSIT2 { get; set; }
        public virtual OCCENUMERATION OCCENUMERATION { get; set; }
        public virtual ICollection<OCCEVENTLOG> OCCEVENTLOG { get; set; }
    }
}
