//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardChequeModule.OraDBCardInfo {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OraDBCardInfo.OradbaccessSoap")]
    public interface OradbaccessSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCCardDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCCardDetail(string cardno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCCardDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetCCardDetailAsync(string cardno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLankaBanglaF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetLankaBanglaF(string lngData, System.DateTime sysdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLankaBanglaF", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetLankaBanglaFAsync(string lngData, System.DateTime sysdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLankaBanglaFDateRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetLankaBanglaFDateRange(string lngData, System.DateTime sysdate, System.DateTime to_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLankaBanglaFDateRange", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetLankaBanglaFDateRangeAsync(string lngData, System.DateTime sysdate, System.DateTime to_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetRate(string strCurrency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetRateAsync(string strCurrency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHBInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetHBInfo(string stracc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHBInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetHBInfoAsync(string stracc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLankaBanglaFVisa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetLankaBanglaFVisa(string lngData, System.DateTime sysdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLankaBanglaFVisa", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetLankaBanglaFVisaAsync(string lngData, System.DateTime sysdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLankaBanglaFMoney", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetLankaBanglaFMoney(string lngData, System.DateTime sysdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLankaBanglaFMoney", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetLankaBanglaFMoneyAsync(string lngData, System.DateTime sysdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetONEBankVisa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetONEBankVisa(string lngData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetONEBankVisa", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetONEBankVisaAsync(string lngData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRJSCTran", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetRJSCTran(string strKey, string lngData, System.DateTime sysdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRJSCTran", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetRJSCTranAsync(string strKey, string lngData, System.DateTime sysdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRJSCTranDateRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetRJSCTranDateRange(string strKey, string lngData, System.DateTime sysdate, System.DateTime to_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRJSCTranDateRange", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetRJSCTranDateRangeAsync(string strKey, string lngData, System.DateTime sysdate, System.DateTime to_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRJSCTranDateRangeNew", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetRJSCTranDateRangeNew(string strKey, long lngData, string sysdate, string to_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRJSCTranDateRangeNew", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetRJSCTranDateRangeNewAsync(string strKey, long lngData, string sysdate, string to_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLCARTran", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetLCARTran(string lngData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLCARTran", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetLCARTranAsync(string lngData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLCMaster", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetLCMaster();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLCMaster", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetLCMasterAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCifsDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCifsDetail();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCifsDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetCifsDetailAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPHTran", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPHTran(string lngData, System.DateTime sysdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPHTran", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetPHTranAsync(string lngData, System.DateTime sysdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCTRTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCTRTransaction(string strAcno, System.DateTime dtFrom, System.DateTime dtTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCTRTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetCTRTransactionAsync(string strAcno, System.DateTime dtFrom, System.DateTime dtTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCTRAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCTRAccount(System.DateTime dtFrom, System.DateTime dtTo, string strDrCr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCTRAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetCTRAccountAsync(System.DateTime dtFrom, System.DateTime dtTo, string strDrCr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCTRAccountDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCTRAccountDetail(string strAccno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCTRAccountDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetCTRAccountDetailAsync(string strAccno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCTRSignatoryDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCTRSignatoryDetail(string strAccno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCTRSignatoryDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetCTRSignatoryDetailAsync(string strAccno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCTRIndividualAccDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCTRIndividualAccDetail(string strAccno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCTRIndividualAccDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetCTRIndividualAccDetailAsync(string strAccno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustAccType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCustAccType(string strAccno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustAccType", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetCustAccTypeAsync(string strAccno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccountDetailForBAT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAccountDetailForBAT(string strCurrDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccountDetailForBAT", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAccountDetailForBATAsync(string strCurrDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OradbaccessSoapChannel : CardChequeModule.OraDBCardInfo.OradbaccessSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OradbaccessSoapClient : System.ServiceModel.ClientBase<CardChequeModule.OraDBCardInfo.OradbaccessSoap>, CardChequeModule.OraDBCardInfo.OradbaccessSoap {
        
        public OradbaccessSoapClient() {
        }
        
        public OradbaccessSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OradbaccessSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OradbaccessSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OradbaccessSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataTable GetCCardDetail(string cardno) {
            return base.Channel.GetCCardDetail(cardno);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetCCardDetailAsync(string cardno) {
            return base.Channel.GetCCardDetailAsync(cardno);
        }
        
        public System.Data.DataTable GetLankaBanglaF(string lngData, System.DateTime sysdate) {
            return base.Channel.GetLankaBanglaF(lngData, sysdate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetLankaBanglaFAsync(string lngData, System.DateTime sysdate) {
            return base.Channel.GetLankaBanglaFAsync(lngData, sysdate);
        }
        
        public System.Data.DataTable GetLankaBanglaFDateRange(string lngData, System.DateTime sysdate, System.DateTime to_date) {
            return base.Channel.GetLankaBanglaFDateRange(lngData, sysdate, to_date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetLankaBanglaFDateRangeAsync(string lngData, System.DateTime sysdate, System.DateTime to_date) {
            return base.Channel.GetLankaBanglaFDateRangeAsync(lngData, sysdate, to_date);
        }
        
        public System.Data.DataTable GetRate(string strCurrency) {
            return base.Channel.GetRate(strCurrency);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetRateAsync(string strCurrency) {
            return base.Channel.GetRateAsync(strCurrency);
        }
        
        public System.Data.DataTable GetHBInfo(string stracc) {
            return base.Channel.GetHBInfo(stracc);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetHBInfoAsync(string stracc) {
            return base.Channel.GetHBInfoAsync(stracc);
        }
        
        public System.Data.DataTable GetLankaBanglaFVisa(string lngData, System.DateTime sysdate) {
            return base.Channel.GetLankaBanglaFVisa(lngData, sysdate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetLankaBanglaFVisaAsync(string lngData, System.DateTime sysdate) {
            return base.Channel.GetLankaBanglaFVisaAsync(lngData, sysdate);
        }
        
        public System.Data.DataTable GetLankaBanglaFMoney(string lngData, System.DateTime sysdate) {
            return base.Channel.GetLankaBanglaFMoney(lngData, sysdate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetLankaBanglaFMoneyAsync(string lngData, System.DateTime sysdate) {
            return base.Channel.GetLankaBanglaFMoneyAsync(lngData, sysdate);
        }
        
        public System.Data.DataTable GetONEBankVisa(string lngData) {
            return base.Channel.GetONEBankVisa(lngData);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetONEBankVisaAsync(string lngData) {
            return base.Channel.GetONEBankVisaAsync(lngData);
        }
        
        public System.Data.DataTable GetRJSCTran(string strKey, string lngData, System.DateTime sysdate) {
            return base.Channel.GetRJSCTran(strKey, lngData, sysdate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetRJSCTranAsync(string strKey, string lngData, System.DateTime sysdate) {
            return base.Channel.GetRJSCTranAsync(strKey, lngData, sysdate);
        }
        
        public System.Data.DataTable GetRJSCTranDateRange(string strKey, string lngData, System.DateTime sysdate, System.DateTime to_date) {
            return base.Channel.GetRJSCTranDateRange(strKey, lngData, sysdate, to_date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetRJSCTranDateRangeAsync(string strKey, string lngData, System.DateTime sysdate, System.DateTime to_date) {
            return base.Channel.GetRJSCTranDateRangeAsync(strKey, lngData, sysdate, to_date);
        }
        
        public System.Data.DataTable GetRJSCTranDateRangeNew(string strKey, long lngData, string sysdate, string to_date) {
            return base.Channel.GetRJSCTranDateRangeNew(strKey, lngData, sysdate, to_date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetRJSCTranDateRangeNewAsync(string strKey, long lngData, string sysdate, string to_date) {
            return base.Channel.GetRJSCTranDateRangeNewAsync(strKey, lngData, sysdate, to_date);
        }
        
        public System.Data.DataTable GetLCARTran(string lngData) {
            return base.Channel.GetLCARTran(lngData);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetLCARTranAsync(string lngData) {
            return base.Channel.GetLCARTranAsync(lngData);
        }
        
        public System.Data.DataTable GetLCMaster() {
            return base.Channel.GetLCMaster();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetLCMasterAsync() {
            return base.Channel.GetLCMasterAsync();
        }
        
        public System.Data.DataTable GetCifsDetail() {
            return base.Channel.GetCifsDetail();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetCifsDetailAsync() {
            return base.Channel.GetCifsDetailAsync();
        }
        
        public System.Data.DataTable GetPHTran(string lngData, System.DateTime sysdate) {
            return base.Channel.GetPHTran(lngData, sysdate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetPHTranAsync(string lngData, System.DateTime sysdate) {
            return base.Channel.GetPHTranAsync(lngData, sysdate);
        }
        
        public System.Data.DataTable GetCTRTransaction(string strAcno, System.DateTime dtFrom, System.DateTime dtTo) {
            return base.Channel.GetCTRTransaction(strAcno, dtFrom, dtTo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetCTRTransactionAsync(string strAcno, System.DateTime dtFrom, System.DateTime dtTo) {
            return base.Channel.GetCTRTransactionAsync(strAcno, dtFrom, dtTo);
        }
        
        public System.Data.DataTable GetCTRAccount(System.DateTime dtFrom, System.DateTime dtTo, string strDrCr) {
            return base.Channel.GetCTRAccount(dtFrom, dtTo, strDrCr);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetCTRAccountAsync(System.DateTime dtFrom, System.DateTime dtTo, string strDrCr) {
            return base.Channel.GetCTRAccountAsync(dtFrom, dtTo, strDrCr);
        }
        
        public System.Data.DataTable GetCTRAccountDetail(string strAccno) {
            return base.Channel.GetCTRAccountDetail(strAccno);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetCTRAccountDetailAsync(string strAccno) {
            return base.Channel.GetCTRAccountDetailAsync(strAccno);
        }
        
        public System.Data.DataTable GetCTRSignatoryDetail(string strAccno) {
            return base.Channel.GetCTRSignatoryDetail(strAccno);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetCTRSignatoryDetailAsync(string strAccno) {
            return base.Channel.GetCTRSignatoryDetailAsync(strAccno);
        }
        
        public System.Data.DataTable GetCTRIndividualAccDetail(string strAccno) {
            return base.Channel.GetCTRIndividualAccDetail(strAccno);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetCTRIndividualAccDetailAsync(string strAccno) {
            return base.Channel.GetCTRIndividualAccDetailAsync(strAccno);
        }
        
        public System.Data.DataTable GetCustAccType(string strAccno) {
            return base.Channel.GetCustAccType(strAccno);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetCustAccTypeAsync(string strAccno) {
            return base.Channel.GetCustAccTypeAsync(strAccno);
        }
        
        public System.Data.DataTable GetAccountDetailForBAT(string strCurrDate) {
            return base.Channel.GetAccountDetailForBAT(strCurrDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAccountDetailForBATAsync(string strCurrDate) {
            return base.Channel.GetAccountDetailForBATAsync(strCurrDate);
        }
    }
}
